env:
  browser: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2017
extends:
  - 'eslint:recommended'
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
  no-console:
    - off
  no-unused-vars:
    - warn
  parsing:
    - warn
  no-irregular-whitespace:
    - warn
  no-mixed-spaces-and-tabs:
    - warn
